[package]
name = "test-utils"
version = "0.1.0"
edition = "2021"
description = "Shared testing utilities for the Ciphr platform."
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
tempfile = { workspace = true }

[dev-dependencies]
proptest = "1.4.0"
