name: Welcome First-time Contributors

on:
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    name: Welcome Contributor
    runs-on: ubuntu-latest
    steps:
      - name: Send welcome message
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Hello @${{ github.actor }} and thank you for your contribution! 🎉

            We are thrilled to have you here. Please make sure to read our contributing guidelines, and don't hesitate to ask if you have any questions. We look forward to reviewing your issue.
          pr-message: |
            Hello @${{ github.actor }} and thank you for your contribution! 🎉

            We are thrilled to have you here. Please make sure to read our contributing guidelines, and don't hesitate to ask if you have any questions. We look forward to reviewing your pull request. 